### ISSUE TITLE
Clients may initialise connection multiple times if packets are dropped

### ISSUE THREAD

**Issue by darkrilin** [darkrilin/woahzone#5]
This causes ghost characters to stick around spawn for a bit and throws errors in everybody else's consoles. I'm sure it could contribute to a memory leak too if unchecked.

**Comment by darkrilin** [comment]
I'd just like to clarify that "ghost characters" doesn't literally mean the ghost playermodel, but a player entity that doesn't have a connected client and is sticking around for some reason.

**Comment by Datenyan** [comment]
Is there a way to potentially create a unique ID for each browser instance that could be sent with the connect request to the signalling server? If so, you could store these IDs and check for them on a connect event, and force a disconnect of an existing ID if necessary

**Comment by darkrilin** [comment]
Each client is generating a uniqueish ID when the page is initially loaded...
`const ID = Math.round(Date.now() * Math.random() + 1);`
This is sent through when the client establishes a connection (sending 'join' to the server), and it's what the server uses to keep track of connections/players.

Looking at [the join function on line 46 of app.js](https://github.com/darkrilin/woahzone/blob/801365de04c631db5748a305a49a035434537186/app.js#L46), I'm not doing anything when there's an ID collision, so this is where a fix would probably be appropriately implemented on the server side. If this is handled properly, clients shouldn't get any errors on their ends either, as they'll be notified of the user ID correctly.
